image:
  repository: "gotenberg/gotenberg"
  tag: "8.31.0@sha256:f0d86e8a1dbc7b33a5a65cb251d02bb271a48ffa989da3feb5ed7d954fe4d4b3"

ports:
  - name: main
    containerPort: 3000

health:
  path: /health

command:
  - "gotenberg"

args:
  - "--chromium-disable-javascript=true"
  - "--chromium-allow-list=file:///tmp/.*"
