image:
  repository: "gotenberg/gotenberg"
  tag: "8.35.0@sha256:a16a14e1f18a71405624bc028e90d4ef50ea774c352b303639c10bf7b141f760"

ports:
  - name: main
    containerPort: 3000

health:
  path: /health

command:
  - "gotenberg"

args:
  - "--chromium-disable-javascript=true"
  - "--chromium-allow-list=file:///tmp/.*"
