image:
  repository: "gotenberg/gotenberg"
  tag: "8.30.0@sha256:d3c9e0ed2450c9a4631de6d14b51c75fd6051512c33aa8a6df622f085592c48b"

ports:
  - name: main
    containerPort: 3000

health:
  path: /health

command:
  - "gotenberg"

args:
  - "--chromium-disable-javascript=true"
  - "--chromium-allow-list=file:///tmp/.*"
