image:
  repository: "ghcr.io/hotio/sonarr"
  tag: "release-4.0.19.2979@sha256:b1429fd40950a7789e74423bd61695467ad760667c173402b2b917d4fc8ec2d6"

ports:
  - name: main
    containerPort: 8989

gateway:
  host: sonarr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/sonarr
    containerPath: /config
  - name: downloads-torrent
    hostPath: /srv/downloads/torrent
    containerPath: /downloads/torrent
  - name: downloads-usenet
    hostPath: /srv/downloads/usenet
    containerPath: /downloads/usenet
  - name: series
    hostPath: /srv/hdd/multimedia/Serien-Sonarr
    containerPath: /series

homepage:
  name: Sonarr
  group: Indexer
  description: Serien Manager
  icon: sonarr.svg
  weight: 13
