image:
  repository: "ghcr.io/hotio/sonarr"
  tag: "release-4.0.19.2979@sha256:71d939c562a273767d97f51516f349e8459542cf868058e4b49891513210bdd5"

ports:
  - name: main
    containerPort: 8989

gateway:
  host: sonarr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/sonarr
    containerPath: /config
  - name: downloads-torrent
    hostPath: /srv/downloads/torrent
    containerPath: /downloads/torrent
  - name: downloads-usenet
    hostPath: /srv/downloads/usenet
    containerPath: /downloads/usenet
  - name: series
    hostPath: /srv/hdd/multimedia/Serien-Sonarr
    containerPath: /series

homepage:
  name: Sonarr
  group: Manager
  description: Serien Manager
  icon: sonarr.svg
  weight: 2
