image:
  repository: "ghcr.io/hotio/sonarr"
  tag: "release-4.0.20.3014@sha256:e6052fce3715b3bdc8ad517aae6f2dfb5e6bcf68f71585274099236aa47365a2"

ports:
  - name: main
    containerPort: 8989

gateway:
  host: sonarr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/sonarr
    containerPath: /config
  - name: downloads-torrent
    hostPath: /srv/downloads/torrent
    containerPath: /downloads/torrent
  - name: downloads-usenet
    hostPath: /srv/downloads/usenet
    containerPath: /downloads/usenet
  - name: series
    hostPath: /srv/hdd/multimedia/Serien-Sonarr
    containerPath: /series

homepage:
  name: Sonarr
  group: Manager
  description: Serien Manager
  icon: sonarr.svg
  weight: 2
