image:
  repository: "mempool/electrs"
  tag: "v3.3.0@sha256:de9dd2f5a328d5f464936dc4128d848f9b8bf72221ab3c9b8e2949df50899b74"

args:
  - "--lightmode"
  - "--http-addr=0.0.0.0:3000"
  - "--db-dir=/data"
  - "--daemon-rpc-addr=bitcoin-node:8332"
  - "--daemon-dir=/bitcoin"
  - "-vvv"

hostPaths:
  - name: data
    hostPath: /srv/nvme/scrap-data/electrs
    containerPath: /data
  - name: bitcoin
    hostPath: /srv/nvme/scrap-data/bitcoin
    containerPath: /bitcoin
    readOnly: true

ports: 
- name: main
  containerPort: 3000

health:
  type: TCP

securityContext:
  runAsUser: 5000
