image:
  repository: "ghcr.io/gethomepage/homepage"
  tag: "v2.2.0@sha256:753eeb0cc22ab7baad39ed47cbd1aae14e193dd1b264e965f193a9ea1d1e1bdd"

config:
  bookmarks: {}
  kubernetes:
    mode: cluster
    gateway: true
  services:
    - "Security & Identity":
        - Unifi Gateway:
            description: Firewall
            href: https://192.168.0.1/network/default/dashboard
            icon: unifi.svg
            weight: 3
        - AdGuard Home:
            description: DNS Server
            href: http://192.168.0.2
            icon: adguard-home.svg
            weight: 4
    - "Home & Utilities":
        - "Home Assistant":
            description: Smart Home
            href: http://ha.wagner.gg
            icon: home-assistant.svg
            weight: 1
        - Valetudo:
            description: Robotic Vacuum
            href: http://192.168.0.11
            icon: valetudo.svg
            weight: 2
    - Media:
        - Plex:
            app: plex
            description: Media Center
            href: https://app.plex.tv/desktop
            icon: plex.svg
            namespace: media
            weight: 1
    - Infrastructure:
        - Portainer:
            description: Pi Container Management
            href: https://192.168.0.2:9443
            icon: portainer.svg
            weight: 2
  settings:
    color: neutral
    hideVersion: true
    iconStyle: theme
    layout:
      - Security & Identity:
          icon: mdi-shield-lock-outline
      - Personal & Finance:
          icon: mdi-cash-multiple
      - Home & Utilities:
          icon: mdi-home-outline
      - Files & Docs:
          icon: mdi-folder-multiple-outline
      - Media:
          icon: mdi-filmstrip-box
      - Manager:
          icon: mdi-download-multiple
      - Downloads:
          icon: mdi-download-outline
      - Infrastructure:
          icon: mdi-server
    target: _self
    theme: dark
    title: Homelab
  widgets:
    - search:
        provider: google
        target: _blank

enableRbac: true

extraClusterRoles:
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
      - gateways
    verbs:
      - get
      - list

serviceAccount:
  create: true

env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: home.wagner.gg
