image:
  repository: "tomsquest/docker-radicale"
  tag: "3.7.3.0@sha256:265195d889c122bb64367a84ce36ff5dc3ab88b6f5a26321af7d41be6a5da2d0"

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/radicale-config
    containerPath: /config
  - name: data
    hostPath: /srv/nvme/container-data/radicale-data
    containerPath: /data

ports:
  - name: main
    containerPort: 5232

gateway:
  host: radicale.wagner.gg
  public: true

homepage:
  name: Radicale
  group: Organization
  description: Lightweight CalDAV+CardDAV server
  icon: radicale.png
  weight: 30
