image:
  repository: "tomsquest/docker-radicale"
  tag: "3.8.1.0@sha256:6e9f65882fe71af556b01cc1eb8e1307dba55a273db55504fa22d275dedec3ab"

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/radicale-config
    containerPath: /config
  - name: data
    hostPath: /srv/nvme/container-data/radicale-data
    containerPath: /data

ports:
  - name: main
    containerPort: 5232

gateway:
  host: radicale.wagner.gg
  public: true

homepage:
  name: Radicale
  group: Files & Docs
  description: Lightweight CalDAV+CardDAV server
  icon: radicale.png
  weight: 3
