image:
  repository: "tomsquest/docker-radicale"
  tag: "3.7.0.0@sha256:fc5f32e378960af5d5a9be0bc13a91186f103187335f63ab06b33ad5b922b371"

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/radicale-config
    containerPath: /config
  - name: data
    hostPath: /srv/nvme/container-data/radicale-data
    containerPath: /data

ports:
  - name: main
    containerPort: 5232

gateway:
  host: radicale.wagner.gg
  public: true

homepage:
  name: Radicale
  group: Organization
  description: Lightweight CalDAV+CardDAV server
  icon: radicale.png
  weight: 30
