image:
  repository: "traefik/whoami"
  tag: "v1.12.0@sha256:c4717a8d1f0134a7444e24f881160e033991f23027c6c5a9a3f8fd22e70d1d44"

ports:
  - name: main
    containerPort: 80

gateway:
  host: whoami.wagner.gg
  public: true
