image:
  repository: "ghcr.io/flaresolverr/flaresolverr"
  tag: "v3.5.2@sha256:c80ae007ce2ccdcd217a12426e4f039ef763ff90738c808d38810c3e59323767"

ports:
  - name: main
    containerPort: 8191

health:
  path: /health
