image:
  repository: "ghcr.io/flaresolverr/flaresolverr"
  tag: "v3.5.0@sha256:139dfee1c6f89249c8d665d1333a42e8ec74ec0a86bc6bb1c8461e10d3a66a47"

ports:
  - name: main
    containerPort: 8191

health:
  path: /health
