image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

serviceAccount:
  annotations: {}

podLabels: {}
podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

hostNetwork: false

ports: []
# - name: ""
#   containerPort: 0
#   protocol: TCP

service:
  type: ClusterIP
  externalTrafficPolicy: ""
  loadBalancerIP: ""
  loadBalancerClass: ""

health:
  enabled: true
  startupProbeSeconds: 60
  port: main
  type: HTTP
  path: /

gateway:
  host: ""
  path: /
  public: false
  publicPath: /
  port: main
  publicRules: {}

oidc:
  clientId: ""
  clientSecret: ""

replicas: 1
strategyType: Recreate

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

terminationGracePeriodSeconds: 30

command: []

args: []

envs: []

secretEnvs: []

configMaps: []
# - name: ""
#   defaultMode: 0644
#   mountPath: ""
#   subPath: ""
#   content: ""

hostPaths: []
# - name: ""
#   hostPath: ""
#   containerPath: ""
#   readOnly: false
#   type: "DirectoryOrCreate"

emptyDirs: []

# - name: ""
#   containerPath: ""

initContainers: []

envsubst:
  image:
    repository: ghcr.io/skaronator/envsubst
    tag: "latest@sha256:372cf36d3d7c7ac06517aa4012fe7c19836e9c62ee3a4fe8e39e7423c49a4b15"
  files: []
  # - src:
  #   dest:

database:
  enabled: false
  resources: {}
  hostPath: ""
  rootPassword: ""
  userPassword: ""
  type: mariadb
  mariadb:
    image:
      repository: mariadb
      tag: "12.3.2@sha256:759869cb6f003234a95c6384cdee245b4bce7de26913fe607a8110362c0c007d"
    backup:
      schedule: "0 4 * * *"
      image:
        repository: fradelg/mysql-cron-backup
        tag: "latest@sha256:d9b9b1514ef5f879031ea88c656c0b64acb98bb787f401c2fc3f62ed6fafb308"
  postgresql:
    image:
      repository: postgres
      tag: "17.11@sha256:f86c774c7a51d0f05133f2ab70e4c384b589170458ab1df1ba83426d7cc30da7"
    backup:
      schedule: "0 4 * * *"
      image:
        repository: prodrigestivill/postgres-backup-local
        tag: "17@sha256:e803bd9eb4bfb42e9b3e74ba411227f3d55da292905800395659cc579b6641e8"

helper:
  image:
    repository: busybox
    tag: "1.38.0@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616"

wait4x:
  image:
    repository: wait4x/wait4x
    tag: "3.6.0@sha256:bec7ac18547781d854562c3729d3195c3880116d6758c49fdf4573ad58805f14"

vpn:
  image:
    repository: qmcgaw/gluetun
    tag: "v3.41.3@sha256:fa19cc76b2af13d57a8d3dc3066f2ada061b1c761b8aecf989b3877c0486e027"
  enabled: false
  envs: []
  secretEnvs: []

homepage:
  name: ""
  description: ""
  group: ""
  icon: ""
  weight: 50
  widgetType: ""
