image:
  repository: "ghcr.io/skaronator/zrepl"
  tag: "main@sha256:b5486b865515a6b0067677194d079c3666d360ece5834bbda290b16c97e25701"

securityContext:
  privileged: true
  capabilities:
    add:
      - SYS_ADMIN

configMaps:
  - name: config
    mountPath: /etc/zrepl
    subPath: zrepl.yml
    content:
      global:
        logging:
          - format: human
            level: info
            type: stdout
      jobs:
        - filesystems:
            hdd<: true
            # except root, backup and multimedia
            hdd: false
            hdd/backup: false
            hdd/multimedia: false
            # backup everything from nvme
            nvme<: true
            # except root and scrap-data
            nvme: false
            nvme/scrap-data: false
          name: longterm
          pruning:
            keep:
              - grid: 1x24h(keep=all) | 14x1d | 3x30d
                regex: ^longterm_.*$
                type: grid
          snapshotting:
            cron: 0 * * * *
            prefix: longterm_
            type: cron
          type: snap
        - filesystems:
            # backup everything from zroot
            zroot<: true
            # except root and backup
            zroot: false
            hdd/multimedia: true
          name: midterm
          pruning:
            keep:
              - grid: 1x24h(keep=all) | 14x1d
                regex: ^midterm_.*$
                type: grid
          snapshotting:
            cron: 0 * * * *
            prefix: midterm_
            type: cron
          type: snap
        - filesystems:
            # Backup everything from downloads
            downloads<: true
            # except root volume
            downloads: false
            hdd/backup: true
            nvme/scrap-data: true
          name: shortterm
          pruning:
            keep:
              - grid: 1x24h(keep=all) | 3x1d
                regex: ^shortterm_.*$
                type: grid
          snapshotting:
            cron: 0 * * * *
            prefix: shortterm_
            type: cron
          type: snap
