apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "restic-backup.name" . }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    {{- include "restic-backup.labels" . | nindent 4 }}
spec:
  encryptedData:
    REPOSITORY_BASE_PATH: {{ .Values.restic.basePath | quote }}
    RESTIC_PASSWORD: {{ .Values.restic.password | quote }}
    AWS_ACCESS_KEY_ID: {{ .Values.restic.accessKeyId | quote }}
    AWS_SECRET_ACCESS_KEY: {{ .Values.restic.secretKeyId | quote }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
