image:
  repository: "ghcr.io/jellyfin/jellyfin"
  tag: "12.0@sha256:74f4d87d9cf262c52d62be6be265c0355c6a7e21d0477ab6c654a49a4f8b1fd4"

ports:
  - name: main
    containerPort: 8096

gateway:
  host: jellyfin.wagner.gg

health:
  path: /

envs:
  - JELLYFIN_PublishedServerUrl: https://jellyfin.wagner.gg

resources:
  limits:
    gpu.intel.com/i915: "1"

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/jellyfin
    containerPath: /config
  - name: cache
    hostPath: /srv/nvme/scrap-data/jellyfin-cache
    containerPath: /cache
  - name: multimedia
    hostPath: /srv/hdd/multimedia
    containerPath: /srv/multimedia
    readOnly: true
  - name: music
    hostPath: /srv/nvme/music
    containerPath: /srv/music
    readOnly: true

homepage:
  name: Jellyfin
  group: Media
  description: Media Center
  icon: jellyfin.svg
  weight: 2
