image:
  repository: "ghcr.io/jellyfin/jellyfin"
  tag: "10.11.11@sha256:45f648c382a0c8b552582fcea40e95cb17c5d475473a891cba0eb7523fb92112"

ports:
  - name: main
    containerPort: 8096

gateway:
  host: jellyfin.wagner.gg

health:
  path: /

envs:
  - JELLYFIN_PublishedServerUrl: https://jellyfin.wagner.gg

resources:
  limits:
    gpu.intel.com/i915: "1"

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/jellyfin
    containerPath: /config
  - name: cache
    hostPath: /srv/nvme/scrap-data/jellyfin-cache
    containerPath: /cache
  - name: multimedia
    hostPath: /srv/hdd/multimedia
    containerPath: /srv/multimedia
    readOnly: true
  - name: music
    hostPath: /srv/nvme/music
    containerPath: /srv/music
    readOnly: true

homepage:
  name: Jellyfin
  group: Media
  description: Media Center
  icon: jellyfin.svg
  weight: 10
