image:
  repository: "ghcr.io/jellyfin/jellyfin"
  tag: "12.1@sha256:008ec8024bdaaa6f0a3f0de468e185633eeba9d67c56936e8dbf5ef6b8d6200f"

ports:
  - name: main
    containerPort: 8096

gateway:
  host: jellyfin.wagner.gg

health:
  path: /

envs:
  - JELLYFIN_PublishedServerUrl: https://jellyfin.wagner.gg

resources:
  limits:
    gpu.intel.com/i915: "1"

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/jellyfin
    containerPath: /config
  - name: cache
    hostPath: /srv/nvme/scrap-data/jellyfin-cache
    containerPath: /cache
  - name: multimedia
    hostPath: /srv/hdd/multimedia
    containerPath: /srv/multimedia
    readOnly: true
  - name: music
    hostPath: /srv/nvme/music
    containerPath: /srv/music
    readOnly: true

homepage:
  name: Jellyfin
  group: Media
  description: Media Center
  icon: jellyfin.svg
  weight: 2
