image:
  repository: "ghcr.io/usememos/memos"
  tag: "0.26.2"

hostPaths:
  - name: data
    hostPath: /srv/nvme/container-data/memos
    containerPath: /var/opt/memos

ports:
  - name: main
    containerPort: 5230

gateway:
  host: memos.wagner.gg
  public: true

homepage:
  name: Memos
  group: Cloud
  description: Start taking notes!
  icon: memos.svg
  weight: 12
