image:
  repository: "ghcr.io/usememos/memos"
  tag: "0.27.0@sha256:9d07dce448f0266b0a2125f0772eeb3ae04d2f8edba90c043f5f309bc98fcdb9"

hostPaths:
  - name: data
    hostPath: /srv/nvme/container-data/memos
    containerPath: /var/opt/memos

ports:
  - name: main
    containerPort: 5230

gateway:
  host: memos.wagner.gg
  public: true

homepage:
  name: Memos
  group: Cloud
  description: Start taking notes!
  icon: memos.svg
  weight: 12
