image:
  repository: "ghcr.io/usememos/memos"
  tag: "0.27.1@sha256:71048ab89888696e7f37956920c712d2f70fae9c180d4086cd1e3ae3da06a6cb"

hostPaths:
  - name: data
    hostPath: /srv/nvme/container-data/memos
    containerPath: /var/opt/memos

ports:
  - name: main
    containerPort: 5230

gateway:
  host: memos.wagner.gg
  public: true

homepage:
  name: Memos
  group: Cloud
  description: Start taking notes!
  icon: memos.svg
  weight: 12
