image:
  repository: "ghcr.io/open-webui/open-webui"
  tag: "v0.11.4@sha256:9591b13f13843c7721c2b8eaf7382846c81b3ffe126526d1888d1fed50c6a33f"

ports:
  - name: main
    containerPort: 3000

health:
  path: /

gateway:
  host: chat.wagner.gg

hostPaths:
  - name: data
    hostPath: /srv/nvme/container-data/open-webui
    containerPath: /app/backend/data
