image:
  repository: "ollama/ollama"
  tag: "0.40.2@sha256:b86366bb528bbf7f1424435d165028497a5b69bf6ddb4fa5a87102e2b79f44fb"

ports:
  - name: main
    containerPort: 11434

health:
  path: /api/tags

hostPaths:
  - name: data
    hostPath: /srv/nvme/container-data/ollama
    containerPath: /root/.ollama
