image:
  repository: "ollama/ollama"
  tag: "0.40.3@sha256:adca95a12c2b386a8f9a995e7fa0600e187e3323b5e5522f5a6c3b1ec73eff99"

ports:
  - name: main
    containerPort: 11434

health:
  path: /api/tags

envs:
  - OLLAMA_NUM_CTX: 8192

hostPaths:
  - name: data
    hostPath: /srv/nvme/container-data/ollama
    containerPath: /root/.ollama
