image:
  repository: "b3log/siyuan"
  tag: "v3.6.0@sha256:79064edd0b819a95104dff4d8b488e2a3752d17af0e0f442c0d25f7798dde707"

hostPaths:
  - name: data
    hostPath: /srv/nvme/container-data/siyuan
    containerPath: /data

health:
  path: /

envs:
  - SIYUAN_WORKSPACE_PATH: /data

secretEnvs:
  - SIYUAN_ACCESS_AUTH_CODE: AgCKzUSM09sN0myiXCgumN8wpWCBaZLhPAvPu4vadkR8EC8pTmkB2Gud0++j0GlMdZlZimmW5zAe2XNmQUxuV5RmDXCvpbmUltU0fnqKWvbAwaaYYpYsSGix1CPvnjdoxlXICiM1W6XMwT2+EfdKSx0aMM0zN54TNHbH5tSQuM1B5US8j1mrC3a508F8qtvWUnEaUPrCAzB3tUSvxNqZonWJUNYuFJTSGWhHCg3c8skBgOltC9PkEi+ndYsZsAsKvLGsfKkE8tW3O1FSjSnD4AQ9RYsgUifqq6EFv0G5gV6HRChLBkKDWD+3O5c9bVR3YGWg/8GQVRdgxqXddKZ31MIei9zk6fesfg37vT22FOzlURN9Cb1kDlwZsrXtb8vhGsxQkuUcHQYzXxBB92GjUCQt8qCpMjSUuq9K58oIef5dAZQN5pvMS7ODnGiClh90ZZOyWpZypSyT2C7ujS74tw4GBlq4ISLoEDMSkSX2PBopl2qX8hIVXFK4YRG7oWs5d10lSXK9tzTH+N92gAplTqUdBGunZ1AMbJXuvsbQJOlDCtXT8NZJ7/bpJzWkDikKY1yIu1pILQ1acIKIUSyS/qcFhR500k3PZ6OJ/C1HcWVK6s1VxH7xKferw0HiRZGybVlyu2l6T5CD4xSqvgGCt3LGNBmENTqGCwLmUOsPIRui8C9WBnRPUi1GrJ/BowgNsRwgHr6AcKjQNU4xu7Z7BLgqaY2bf/70VwUv3aaXSREm0TipEVnrV+CmCQQ1RVBFW22R0g/DQd6G4FeJDT2qWI5I

ports:
  - name: main
    containerPort: 6806

gateway:
  host: siyuan.wagner.gg

homepage:
  name: SiYuan
  group: Cloud
  description: Note Taking
  icon: siyuan.svg
  weight: 12
