image:
  repository: "b3log/siyuan"
  tag: "v3.6.0@sha256:79064edd0b819a95104dff4d8b488e2a3752d17af0e0f442c0d25f7798dde707"

hostPaths:
  - name: data
    hostPath: /srv/nvme/container-data/siyuan
    containerPath: /data

health:
  path: /

envs:
  - SIYUAN_WORKSPACE_PATH: /data

ports:
  - name: main
    containerPort: 6806

gateway:
  host: siyuan.wagner.gg

homepage:
  name: SiYuan
  group: Cloud
  description: Note Taking
  icon: siyuan.svg
  weight: 12
