image:
  repository: "ghcr.io/hotio/radarr"
  tag: "release-6.2.1.10461@sha256:1dae87d74a7356260a5d3b379adc21c8bc0543763a5ff95dd1e0793225f9d06c"

ports:
  - name: main
    containerPort: 7878

gateway:
  host: radarr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/radarr
    containerPath: /config
  - name: downloads-torrent
    hostPath: /srv/downloads/torrent
    containerPath: /downloads/torrent
  - name: downloads-usenet
    hostPath: /srv/downloads/usenet
    containerPath: /downloads/usenet
  - name: movies
    hostPath: /srv/hdd/multimedia/Filme-Radarr
    containerPath: /movies
  - name: live-music
    hostPath: /srv/hdd/multimedia/Live-Konzerte
    containerPath: /live-music

homepage:
  name: Radarr
  group: Indexer
  description: Movie Manager
  icon: radarr.svg
  weight: 12
