image:
  repository: "ghcr.io/hotio/radarr"
  tag: "release-6.1.1.10360@sha256:769450abd3fed087fd1381d138af77513f72fc753e0f5c9aba5e5dbd87410f7b"

ports:
  - name: main
    containerPort: 7878

gateway:
  host: radarr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/radarr
    containerPath: /config
  - name: downloads-torrent
    hostPath: /srv/downloads/torrent
    containerPath: /downloads/torrent
  - name: downloads-usenet
    hostPath: /srv/downloads/usenet
    containerPath: /downloads/usenet
  - name: movies
    hostPath: /srv/hdd/multimedia/Filme-Radarr
    containerPath: /movies
  - name: live-music
    hostPath: /srv/hdd/multimedia/Live-Konzerte
    containerPath: /live-music

homepage:
  name: Radarr
  group: Indexer
  description: Movie Manager
  icon: radarr.svg
  weight: 12
