image:
  repository: "ghcr.io/hotio/radarr"
  tag: "release-6.2.1.10461@sha256:ea78535f2579c308655c76860fdbe30f65c95f31e2de1bc1e65dc9b778530c35"

ports:
  - name: main
    containerPort: 7878

gateway:
  host: radarr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/radarr
    containerPath: /config
  - name: downloads-torrent
    hostPath: /srv/downloads/torrent
    containerPath: /downloads/torrent
  - name: downloads-usenet
    hostPath: /srv/downloads/usenet
    containerPath: /downloads/usenet
  - name: movies
    hostPath: /srv/hdd/multimedia/Filme-Radarr
    containerPath: /movies
  - name: live-music
    hostPath: /srv/hdd/multimedia/Live-Konzerte
    containerPath: /live-music

homepage:
  name: Radarr
  group: Indexer
  description: Movie Manager
  icon: radarr.svg
  weight: 12
