image:
  repository: "boulderbadgedad/soulsync"
  tag: "2.3@sha256:0abec6a5d1af7980937e883df66a7a6fba2cbbc0f0530123abf68e5e4fccf8df"

ports:
  - name: main
    containerPort: 8008

gateway:
  host: soulsync.wagner.gg

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/soulsync-config
    containerPath: /app/config
  - name: data
    hostPath: /srv/nvme/container-data/soulsync-data
    containerPath: /app/data
  - name: downloads
    hostPath: /srv/downloads/soulseek/complete
    containerPath: /app/downloads
  - name: music
    hostPath: /srv/nvme/music
    containerPath: /app/Transfer

homepage:
  name: Soulsync
  group: Indexer
  description: Musik Manager
  weight: 18
