image:
  repository: "ghcr.io/immich-app/immich-machine-learning"
  tag: "v3.3.1@sha256:513c831cfb010ad319341a0c86b42c575a0d5b688d3e8cae346ee624074a58ed"

ports:
  - name: main
    containerPort: 3003

health:
  path: /

hostPaths:
  - name: cache
    hostPath: /srv/nvme/scrap-data/immich-machine-learning
    containerPath: /cache

resources:
  limits:
    gpu.intel.com/i915: "1"

envs:
  - IMMICH_LOG_LEVEL: debug
