image:
  repository: "ghcr.io/immich-app/immich-machine-learning"
  tag: "v3.2.0@sha256:f8b2869891c861a58dde969d86e7ea8a186e6059a55886632ee3249e51fb574a"

ports:
  - name: main
    containerPort: 3003

health:
  path: /

hostPaths:
  - name: cache
    hostPath: /srv/nvme/scrap-data/immich-machine-learning
    containerPath: /cache

resources:
  limits:
    gpu.intel.com/i915: "1"

envs:
  - IMMICH_LOG_LEVEL: debug
