image:
  repository: "ghcr.io/immich-app/immich-machine-learning"
  tag: "v3.2.2@sha256:60dfcf266a9ef3b7376f5678e8c980d4fb61db5fc48c078fe8a326ab1535d60d"

ports:
  - name: main
    containerPort: 3003

health:
  path: /

hostPaths:
  - name: cache
    hostPath: /srv/nvme/scrap-data/immich-machine-learning
    containerPath: /cache

resources:
  limits:
    gpu.intel.com/i915: "1"

envs:
  - IMMICH_LOG_LEVEL: debug
