image:
  repository: "ghcr.io/slskd/slskd"
  tag: "0.24.5@sha256:17ef977563be206f3b5932080b1e23883b2cb39dc9010640f6f39b4eaec887e3"

vpn:
  enabled: true
  secretEnvs:
    - API_KEY: AgB22JxbLHj/pHpjZ5agfio/Nr6Z74rYqb2Mkl9F9lPmIqkSV/3d4QvTo713sQQ9BuTSAZ/HqQgbLKoubWB9vqEB9iFWVxtrO8TVb9StM5ZapqIWR/fbpN/jt8q0QNEyc4AEvJ7UNJvuB7/hUy4ncKmhoJnNCKUqQF0mTnPmYLPe+nQZOAYOANr6xPd+/APB3qpHowk57pq/2kBQVVcFWMEpx2KvMzto/VbpeCXg/T9FydzZ12Biq5Axqt41T0VHYNoDzjc/gtf9lKwkOwLKzR3ch0I89qmHXEgma1Cgl4oe4aHQggA/LDPoYeGBrHbrN14R5cf31YwIWvLaPT4NyZTWNSPHGW2Lov8AJdfokKd4imQ0jJNi6QN37KUnx/ObSGEWx8P+ivMFpt72kdDQyqofgUlmDASdhsfUU+Q8iDQZ5KooeJQcoz9OeprkbxEfM/G8TOfkhd5IC/U5ftbUzX+ocHES1lA3v/pn46eLIifIhNc7HzGv10MbanMTmTNwuaHKeAoPXhjl04eS23BTcUu8U3SghgjAtamoKwRZI3gx+YklFfxNsibczLeQKDsy5HQrfwCjENM/T0VjhNoJE9foxY/goy0ElmbwmDFLTBVVOHdEU16A4VvhLCSijNkE0JEaf89VdD+DgY2w5C/hkk8bGjYHRvyr4Mi0XtcNvLK7FiBrCP/1Vt1r6HOB68z6cbk39SNDadRhCH83/Gj7q8/Ln18yrft/OKVyYlBk7YypO7he3aVgZQ4PUdJm/aPPcgW6AOD28Y3i8zegZcoN4qkP
  envs:
    - VPN_PORT_FORWARDING_UP_COMMAND: |
        curl --location --request PATCH 'http://localhost:5030/api/v0/options' \
        --header 'X-API-Key: $(API_KEY)' \
        --header 'Content-Type: application/json' \
        --data '{
            "soulseek": {
              "listenPort": {{PORT}}
            }
        }'

ports:
  - name: main
    containerPort: 5030

hostPaths:
  - name: app
    hostPath: /srv/nvme/container-data/slskd
    containerPath: /app

gateway:
  host: slskd.wagner.gg

homepage:
  name: SLSKD
  group: Downloader
  description: Soulseek Client
  icon: slskd.svg
  weight: 20

envs:
  - SLSKD_USERNAME: niklas

secretEnvs:
  - SLSKD_PASSWORD: AgBCur/aFp9bX0cfwAJA1wXIxedgjmZMd2EkDsiYV96D1g2b5vNswLK/E8yWCfRGKNSx9DB+1MT4+Bd4ReffZStTaeqOTp5AQOem8M2u2Dz47YUziNgjjMSqRl0YX2ucBmi84Tbk3f9DF99SGA1eTzOI1kblO/wDWlUKzPRqQBXL2iKM+Qx91HneA10iL+0qkKz4y/me2OyUz+OSRFsBU8qDK5NC2uGUZTXFX1erg9JJ6dYH90L4TBWc13j+TYl9NhV2vpMYHx+4P6lsuy+IjuyvFH6i4AbGOvHUys9G+/YZEMPg+rVLVL8Z1Sx+/hK8frksrpi0xF68riw5NL7du/WoCrc3RhWpN8pNc5nw6+mgHa6dysvmgHQgZX+FBEnlddsiGGvCJJmfZv+HTt8Ma1qqOLK/2Dnj96xIcsPvsGae70HYRAheJl2SIYeJdcomquE2n/C8WVRhIE7pYgn3JFC5BxEp2TbB0O+m84dfLUVASoc4YHGQa5+ePvut9VExIlf7R6bx5sBiq7SsSvi0nXOLFPXJ3w1qmJYb8sXurbdrv1ZxyVTwvk/3puDyKoCDqVO6CZ+OZTqz5skceoeJmfVQiER+d0twgD9bTikaM3g5cjjz/q1uz8Lk/Vyl+FHldN8tlh5fBt0J53vHBstSt2kUUFN643QdHtMZ4i5r09mSTcTZHW82A/U+6VQzibaz8LYBv/aGYou0o8czfDqNtxPhDy9e9wASJUTo1eBrwp6J5t6CAupsFVUbQwoL4mVlMc7C20WNChQvEzcimsG1mrF3
  - SLSKD_API_KEY: AgB22JxbLHj/pHpjZ5agfio/Nr6Z74rYqb2Mkl9F9lPmIqkSV/3d4QvTo713sQQ9BuTSAZ/HqQgbLKoubWB9vqEB9iFWVxtrO8TVb9StM5ZapqIWR/fbpN/jt8q0QNEyc4AEvJ7UNJvuB7/hUy4ncKmhoJnNCKUqQF0mTnPmYLPe+nQZOAYOANr6xPd+/APB3qpHowk57pq/2kBQVVcFWMEpx2KvMzto/VbpeCXg/T9FydzZ12Biq5Axqt41T0VHYNoDzjc/gtf9lKwkOwLKzR3ch0I89qmHXEgma1Cgl4oe4aHQggA/LDPoYeGBrHbrN14R5cf31YwIWvLaPT4NyZTWNSPHGW2Lov8AJdfokKd4imQ0jJNi6QN37KUnx/ObSGEWx8P+ivMFpt72kdDQyqofgUlmDASdhsfUU+Q8iDQZ5KooeJQcoz9OeprkbxEfM/G8TOfkhd5IC/U5ftbUzX+ocHES1lA3v/pn46eLIifIhNc7HzGv10MbanMTmTNwuaHKeAoPXhjl04eS23BTcUu8U3SghgjAtamoKwRZI3gx+YklFfxNsibczLeQKDsy5HQrfwCjENM/T0VjhNoJE9foxY/goy0ElmbwmDFLTBVVOHdEU16A4VvhLCSijNkE0JEaf89VdD+DgY2w5C/hkk8bGjYHRvyr4Mi0XtcNvLK7FiBrCP/1Vt1r6HOB68z6cbk39SNDadRhCH83/Gj7q8/Ln18yrft/OKVyYlBk7YypO7he3aVgZQ4PUdJm/aPPcgW6AOD28Y3i8zegZcoN4qkP
