image:
  repository: "ghcr.io/slskd/slskd"
  tag: "0.25.1@sha256:ab9ed50e028b524cefdb7c1dd8ebca368a076e18441ee8ac2326473eb850b4c3"

vpn:
  enabled: true
  envs:
    - HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE: '{"auth":"apikey","apikey":"$(GLUETUN_API_KEY)"}'
    - FIREWALL_VPN_INPUT_PORTS: 28767
  secretEnvs:
    - GLUETUN_API_KEY: AgB71G3PEcVQw2KcrurWR9GfNHFrJlk1tDhzrXY6y6i4iceEji6ainvu3FKIhCl29y8h7Ic2vi284e/QXzbhWH9k8DuUho747foWcxaOAkAiYgW9W1dUYIMkLumPk8B5w2sQ/Y74LVJA1zHdpccXGI/UZM1SR0wQJdD5GstsuCLXy/YbPb8K9NSKY9oXLvBG3yBppc5Wz16aREwQt2Kg4EA78cAr1IgEo744pA1psWGjBj51bauT5vopXBbmkxrWpsegaNdcvxZBQC/KsYmYxurGNaNcjRLnmMppGpV5pcIsvucoZ7RB3x1g2CWR4hON+4vJ6yATW7Pwr+rZsTzrwaff5hYdbi2gQVVuKPEmyrOZ8W1VgG1nL62louDW1VMJcRsBvavnSZM5R0feUNCQF2PrlJ1ZmS+Qm7afWU7NqH7DPY7IJj8z1pJ3JqFKb23bPIugXb4g7GlSGGnWw6HcxfYXpVYtk0IENPM0zP54k5IaUUIeuHiXVUFy/QJi2rz3v8Y7JzFUIBpfOK5nnBEI/7LRAz0Kvzau/ZeBQyHeMBUleXT8up7cV8sagbUNXLAS+8CoE8z0TTCLtllXOLY27VM8xK6G5pDl8m5NUg0CGqX4n2Hzfy2eakCpAG4yPapIXSJ6yYkMk4+KsOGCcatX188ugUyMEDR9psDw/6Anf1+0iBHAkGWkiy13m4VtR4RjTyyLYDReL/gTOLmkZxgKTr4zzEyAUVtIGdWL+E9XklxzWJIS+PiHuaLsz3Bzf9F6Gh5ccDdMHAMzpGw5TpS1eXd2

securityContext:
  runAsUser: 5000
  runAsGroup: 5000
  
ports:
  - name: main
    containerPort: 5030

health:
  path: /health

gateway:
  host: slskd.wagner.gg

hostPaths:
  - name: app
    hostPath: /srv/nvme/container-data/slskd
    containerPath: /app
  - name: downloads-complete
    hostPath: /srv/downloads/soulseek/complete
    containerPath: /downloads/soulseek/complete
  - name: downloads-incomplete
    hostPath: /srv/downloads/soulseek/incomplete
    containerPath: /downloads/soulseek/incomplete
  - name: music
    hostPath: /srv/nvme/music
    containerPath: /music
    readOnly: true

homepage:
  name: SLSKD
  group: Downloader
  description: Soulseek Client
  icon: slskd.svg
  weight: 20

envs:
  - SLSKD_UPLOAD_SPEED_LIMIT: 20000
  - SLSKD_DOWNLOAD_SPEED_LIMIT: 1000
  - SLSKD_SHARED_DIR: /music
  - SLSKD_USERNAME: niklas
  - SLSKD_SLSK_LISTEN_PORT: 28767
  - SLSKD_DOWNLOADS_DIR: /downloads/soulseek/complete
  - SLSKD_INCOMPLETE_DIR: /downloads/soulseek/incomplete
  - SLSKD_REMOTE_FILE_MANAGEMENT: true
  # gluetun integeration
  - SLSKD_VPN: true
  - SLSKD_VPN_PORT_FORWARDING: false # not working with my provider
  - SLSKD_VPN_POLLING_INTERVAL: 2500
  - SLSKD_VPN_GLUETUN_URL: http://localhost:62472

secretEnvs:
  - SLSKD_PASSWORD: AgBCur/aFp9bX0cfwAJA1wXIxedgjmZMd2EkDsiYV96D1g2b5vNswLK/E8yWCfRGKNSx9DB+1MT4+Bd4ReffZStTaeqOTp5AQOem8M2u2Dz47YUziNgjjMSqRl0YX2ucBmi84Tbk3f9DF99SGA1eTzOI1kblO/wDWlUKzPRqQBXL2iKM+Qx91HneA10iL+0qkKz4y/me2OyUz+OSRFsBU8qDK5NC2uGUZTXFX1erg9JJ6dYH90L4TBWc13j+TYl9NhV2vpMYHx+4P6lsuy+IjuyvFH6i4AbGOvHUys9G+/YZEMPg+rVLVL8Z1Sx+/hK8frksrpi0xF68riw5NL7du/WoCrc3RhWpN8pNc5nw6+mgHa6dysvmgHQgZX+FBEnlddsiGGvCJJmfZv+HTt8Ma1qqOLK/2Dnj96xIcsPvsGae70HYRAheJl2SIYeJdcomquE2n/C8WVRhIE7pYgn3JFC5BxEp2TbB0O+m84dfLUVASoc4YHGQa5+ePvut9VExIlf7R6bx5sBiq7SsSvi0nXOLFPXJ3w1qmJYb8sXurbdrv1ZxyVTwvk/3puDyKoCDqVO6CZ+OZTqz5skceoeJmfVQiER+d0twgD9bTikaM3g5cjjz/q1uz8Lk/Vyl+FHldN8tlh5fBt0J53vHBstSt2kUUFN643QdHtMZ4i5r09mSTcTZHW82A/U+6VQzibaz8LYBv/aGYou0o8czfDqNtxPhDy9e9wASJUTo1eBrwp6J5t6CAupsFVUbQwoL4mVlMc7C20WNChQvEzcimsG1mrF3
  - SLSKD_API_KEY: AgB22JxbLHj/pHpjZ5agfio/Nr6Z74rYqb2Mkl9F9lPmIqkSV/3d4QvTo713sQQ9BuTSAZ/HqQgbLKoubWB9vqEB9iFWVxtrO8TVb9StM5ZapqIWR/fbpN/jt8q0QNEyc4AEvJ7UNJvuB7/hUy4ncKmhoJnNCKUqQF0mTnPmYLPe+nQZOAYOANr6xPd+/APB3qpHowk57pq/2kBQVVcFWMEpx2KvMzto/VbpeCXg/T9FydzZ12Biq5Axqt41T0VHYNoDzjc/gtf9lKwkOwLKzR3ch0I89qmHXEgma1Cgl4oe4aHQggA/LDPoYeGBrHbrN14R5cf31YwIWvLaPT4NyZTWNSPHGW2Lov8AJdfokKd4imQ0jJNi6QN37KUnx/ObSGEWx8P+ivMFpt72kdDQyqofgUlmDASdhsfUU+Q8iDQZ5KooeJQcoz9OeprkbxEfM/G8TOfkhd5IC/U5ftbUzX+ocHES1lA3v/pn46eLIifIhNc7HzGv10MbanMTmTNwuaHKeAoPXhjl04eS23BTcUu8U3SghgjAtamoKwRZI3gx+YklFfxNsibczLeQKDsy5HQrfwCjENM/T0VjhNoJE9foxY/goy0ElmbwmDFLTBVVOHdEU16A4VvhLCSijNkE0JEaf89VdD+DgY2w5C/hkk8bGjYHRvyr4Mi0XtcNvLK7FiBrCP/1Vt1r6HOB68z6cbk39SNDadRhCH83/Gj7q8/Ln18yrft/OKVyYlBk7YypO7he3aVgZQ4PUdJm/aPPcgW6AOD28Y3i8zegZcoN4qkP
  - SLSKD_SLSK_USERNAME: AgAUhXDlFMLecvuacDJJ6Qr+akY7Y3xw6XS9H8l3tiohZx6TVV4d37DV8R5Rc4LTgHO+iS4neY2LWFZsUNqUm1w9bPV/AqHpJ+CFD9oD4F0PnWBW33o6S2SWpIn2AggaxS24KsWTj0PoRZqfvjN9zFdt0GR/sW6pwMyX2t2yHYSclgLub/xh2/nF2BkTG9u/I02wlvyqtoZ7EPeT3kru/wWM8q6+nGj9m4ClTjAP9+paTOORfqA6GuZW1w69UTMNTO1js8u5QzBgQ/3HGnJvfRJM0wNN4W/kg8A1ZbUwf3Cg5Tmo+Aix7MrxI/TRYz9xX0VTs0WIeo1/6uTXJQusWMMvCm5Vz7LXKt9pm9kTAl6W6zBpWB+k2e0exbiDcuv+U807drcxkfnynSuQO+gs98zusH9+tibEnyVAuCAW3LgK0hgj+Z/aW784B0X2zAR+Wj1RUj9sJiX5j9rubx3/ydyhC656Ufo0hYvJUGBquyCy4lgA9yoKGyTe+SlV+o47QsY8P4b6At9vkQG2o6Z6sH7kAhtQV0Xjw7njR5d2rZi/mmpgjeX0acVgELXV7eAJRGYuM79UcwrQj9gQr9fUB0NL8+WCRCU6Du5plNz4z9tpovC5PNn/9pGlSU/IbpN3P1La5U1G7kqYptzA/hBR7PaXlCco+NEPSgrsQqxdtHPNPPK7wzH0YDqpZOubKVC46QusPdyr1MPm+GWDdq8=
  - SLSKD_SLSK_PASSWORD: AgBovsCb8cASkTo+gQ0BotA9aJtklXhx4ywrsSnamfqsClN0gvPNIJtLG8NjYHBX3E7VyDntDPI+diar6I8X+1VV94x1bqUp7EvGQnk7ZLqAsZ+8Tt1gyD5sAGFD8bSzReX+CnKbLQDFiImqC2QnRb6zYhYhzXWGpX6fTsyaW1IGp+Tpax7BUh74XQ17j8O2N85wpJh5GRLTkcB2IBM2xH8aJaFJGim+KFKuRdAbdhj4Ea9rLcpY/Be10TpZvOH/7IWp1gDqVLV9n9GWw48NgUfKdPcerydaPhWPp969PeXpoZHaYuxwF5yUqjmB2l0FT8Qe5hKejJMVSxcmCfUzARKLAQqvnLMzjTWJtIbn5WgQijCoMP9ugWJRZWX4+hZodcKOYG0urgq+HCdmkyc2DzxecIo7f2sXfwXT9MmHTRwYiUBOLivBdIpQbLZptoQ0NQHTawsloryhnORK524fvAeTm3bbLOsKQM0h+wbza3wTMhW9gPnIG+h+jwXW1djRylF1d90Dqt9HJYyULgMY1xgIBY8XiY1S1487VRCL7HRNTDQlABpCEnieBiFMPByHX5lrxmi6TAGp02Ed5TYEhXE+rYToZjJTZqHsChpiamhhq50jI2rY38NVBuaxErJs7N5z4eea6dAU0RtmI6qcWpRJ+h8UydvdeeOsBizYFL2mEvsxmrMcsPLNVyq0DH3d+iFBAy1NuFN7EIMaBtcDCmPVIYPLntT3xxP7eOal3zU=
  - SLSKD_VPN_GLUETUN_API_KEY: AgB71G3PEcVQw2KcrurWR9GfNHFrJlk1tDhzrXY6y6i4iceEji6ainvu3FKIhCl29y8h7Ic2vi284e/QXzbhWH9k8DuUho747foWcxaOAkAiYgW9W1dUYIMkLumPk8B5w2sQ/Y74LVJA1zHdpccXGI/UZM1SR0wQJdD5GstsuCLXy/YbPb8K9NSKY9oXLvBG3yBppc5Wz16aREwQt2Kg4EA78cAr1IgEo744pA1psWGjBj51bauT5vopXBbmkxrWpsegaNdcvxZBQC/KsYmYxurGNaNcjRLnmMppGpV5pcIsvucoZ7RB3x1g2CWR4hON+4vJ6yATW7Pwr+rZsTzrwaff5hYdbi2gQVVuKPEmyrOZ8W1VgG1nL62louDW1VMJcRsBvavnSZM5R0feUNCQF2PrlJ1ZmS+Qm7afWU7NqH7DPY7IJj8z1pJ3JqFKb23bPIugXb4g7GlSGGnWw6HcxfYXpVYtk0IENPM0zP54k5IaUUIeuHiXVUFy/QJi2rz3v8Y7JzFUIBpfOK5nnBEI/7LRAz0Kvzau/ZeBQyHeMBUleXT8up7cV8sagbUNXLAS+8CoE8z0TTCLtllXOLY27VM8xK6G5pDl8m5NUg0CGqX4n2Hzfy2eakCpAG4yPapIXSJ6yYkMk4+KsOGCcatX188ugUyMEDR9psDw/6Anf1+0iBHAkGWkiy13m4VtR4RjTyyLYDReL/gTOLmkZxgKTr4zzEyAUVtIGdWL+E9XklxzWJIS+PiHuaLsz3Bzf9F6Gh5ccDdMHAMzpGw5TpS1eXd2
