image:
  repository: "ghcr.io/slskd/slskd"
  tag: "0.24.5"

vpn:
  enabled: true
  # secretEnvs:
  #   - API_KEY: TODO
  # envs:
  #   - VPN_PORT_FORWARDING_UP_COMMAND: |
  #       curl --location --request PATCH 'http://localhost:5030/api/v0/options' \
  #       --header 'X-API-Key: <an API key with administrator role>' \
  #       --header 'Content-Type: application/json' \
  #       --data '{
  #           "soulseek": {
  #             "listenPort": {{PORT}}
  #           }
  #       }'

ports:
  - name: main
    containerPort: 5030

hostPaths:
  - name: app
    hostPath: /srv/nvme/container-data/slskd
    containerPath: /app

gateway:
  host: slskd.wagner.gg

homepage:
  name: SLSKD
  group: Downloader
  description: Soulseek Client
  icon: slskd.svg
  weight: 20

env:
  - SLSKD_REMOTE_CONFIGURATION: true
