image:
  repository: "freikin/dawarich"
  tag: "1.14.4@sha256:2fecbaf093b9544b5733fe972d422100c2bc5be896e706c58eab8bdb6860fe06"

hostPaths:
  - name: public
    hostPath: /srv/nvme/container-data/dawarich-public
    containerPath: /var/app/public
  - name: storage
    hostPath: /srv/nvme/container-data/dawarich-storage
    containerPath: /var/app/storage

health:
  enabled: false

command:
  - sidekiq-entrypoint.sh

args:
  - bundle
  - exec
  - sidekiq

envs:
  - REDIS_URL: redis://dawarich-redis:6379
  - DATABASE_HOST: dawarich-db
  - DATABASE_PORT: 5432
  - DATABASE_USERNAME: dawarich
  - DATABASE_NAME: dawarich
  - PHOTON_API_HOST: app.chibigeo.com/v1/photon
  - PHOTON_API_USE_HTTPS: true

secretEnvs:
  - SECRET_KEY_BASE: AgAarixALXRMeL2anTrm90jupNqbb9COQB7x5yzWfCZ3F1QbEcv7aue6TMQS0n7XWAusSHl/RvGWpiJAg+Q9QVoc/ByZanvQaioOnqkfYBUF2qPZNfzylL6G5Olo5woEsvZ+UuVleuL8HLKxfDnjhYORWbOnURrQpXW2vYXDY/QMML+v2O/glsbS9g+YNV8xOphepd1fT54qbr1z6DluzYkn7As7JxfiJ9/pGH4bJFtij38EeVMQB8EtnkwSexcRQM6fT6H3Grs8ZRN/QNGv7tNj40MlNDKrh2pQB74/eeMDRw39XcFVKmxdR8ZaVUdPwrcPbKFbH2Aaqiaoz+KI0sQ+0AR6aq139PVn8zLfaXpZafhrTk40iNAzbMPcr/opCJL3tOZtseY246a3XTwUuTD/RfAeuGRIM/lNRqju5o41yWGWSeuZCx2o9CY6aFk7+qaC/mel9GzZXwnUXqnpLq4/xyD6VYRRg8Dv1AcQqvIDVDQAgJw6Fa97ijuigVDHsN5JA0SnrDJVyh8OCGaA31xum9iYGQyKC+OHKJ+gF8emnCuQTaoQ2s5GuV1JwezkrT1RmQ0k7vWiHssScP5U4LSULs4ZYxsK89YY/iw3FLG5mtA+9NjJHSPVe2qL8m94o9Y9VZ5sAAFXtTtCtMIPix0BOpTqvFAnWYitzEQV41kago0fVlsrMBLkjtbv+oH7Vg99KLTktsEEc69SWa4q7BkgXg+g1PHLEUfOqfgNPZZ96WHyLB1NUFJX2fm0MG3gRekDLCt8yeHNDzXv0kbGtxVg
  - DATABASE_PASSWORD: AgAZmRa58W0TTagitYM/I5sWdHk2A64mlFlgNpg29OzJ9dam2qXaqlSEAPizBqhziWXgXPByDdQQA4LhTvmmgIt/tlYg2fT4Oqo5Sj6dsQqzul1aYLWUhxCv29GxUva+uGXAUDTpMEcq0KuJRltDzKwn1GrxZqQIWqCMZY/cXQGQd8VY2xkP7mdxJg9Z/mI5F0lRNIYKELI3Cx77vVuGdJf2Z9nMsirFXzBZRN4YsPwE4rs367ghcWtWQeAEGnVuWNnoD9/yNFpMMIpCP+DGZfL8sVAFMe0m8eboJUo13G1p931YVrbaB9wDREmzOvwy72pXcZyx2nIjF3TecHffnRrK9hvL7XbQMToH9T1s7HmxsrbLsKQg7TlUtrEZTF/Buwp94ZB4RWttPot1QbfAmhzvPE10lCHAGhKTgV1MDzqKIUCJ3rC1w8DliLORmjSdfs+MiKpUS3LUjiftzLcZs3V1rdzTz134QH7soSVWeGTWkuvkmU9i1ud8VP2Q6yA0BP8caw5fgpUknpwYJKDQKzfcm7AGd9p6b0d7jr8HeXJmIgdtpowH1egHKOZwBlpAZxRh3HQtEamtjWBwyKBhOZrm/BYCuzJpUdKLUm2cK6fRkR3vkof+c3F6vBxRjEiif3ajZ9Zqky7U6hzGB6q+qWmJjnxlba48uR8ayfNYdQpuYSc4VEGu+ORegsF0nZKzu5Nda3g33ScWpi3zE9onMvz8dkCYwLwBvjpMKwrr9SB3D4+86TSJiCgw/tzwxeB3NEsWe/UiZweHu86lZ1gxEgCG
  - PHOTON_API_KEY: AgAw2jtAsPgk9hfcafGMeeSHTzMEedS10dE9YDp9Z0/zONaENGzY1r3ZtiQLHRgyVjrH/UsMKbhqq0mZCz4061o4mJNM3j+a/OgOkwRi0qRQ+01tpjosSZj3mdfm7fp9lENCyPBtU8aYAG7Q6oBcwZIVMRWHMllfg/5fJ0cP95h+lZPDCTZdN7YKySfW2/7uOnjA6V6k4H5JIKm9JMWkklA0WNBwv7mC6Qq74+ts8ejecEStAPz81WP5OUXC+SwRReH7cxS3Rnxsi0DJ4cKLvNUOmMdR3yJAS/otIGijfIPgXrl1StVN1JYMyE/RWgeXCDdd0+h2qAT3VJmKhYTG/+j5wsVOZW5gWQjEh8JzdeOljFpYZtFJBbwcV925HAHD3Fodgn+Aq3e/DbPP0PGik9Wq7jKTXMqvyRvl+jNJCrk8V8X1ejqtskaNtna5TCDL7ADf+oFb1nTDW3+QzJPZhZX1gu6s0G7qX/4WMRO3xuefhtJUzgKo9A5nALdIhjFbeFMwuGowYyelnlNo2JHtsPDkxE8L+d0pLPCzVAOW5B3k+Gzkd0yDercgwGsFLocRD6HwY5N32wWURvi2PfCVKJEGGR0d0NSnqD89unCueWcpuZ4ChkvPsZowL9tsKbbU9p0lLfMgJd7dP5PdmBscr02tj7WRB2tzaRdtvO19Q1rEuj2++5HcX1rVU712or/o7gUOyd78tdSQ0pATJTNXH0nW2w2DFlNKZCuUDPAOGW1nFce0lg==
