image:
  repository: "ghcr.io/maintainerr/maintainerr"
  tag: "3.10.2@sha256:b6a8c18a1f72d26d0c290bc7002ab766def19eca0f28bc2fa1ab9ae7cd7de06c"

ports:
  - name: main
    containerPort: 6246

gateway:
  host: maintainerr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: data
    hostPath: /srv/nvme/container-data/maintainerr
    containerPath: /opt/data

homepage:
  name: Maintainerr
  group: Indexer
  description: Media Maintainer
  icon: maintainerr.svg
  weight: 30
