image:
  repository: "ghcr.io/maintainerr/maintainerr"
  tag: "3.12.0@sha256:8d52584d00c7e60177fd44ce84c54a448135b74998b5045c69cc957bbcfdcd44"

ports:
  - name: main
    containerPort: 6246

gateway:
  host: maintainerr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: data
    hostPath: /srv/nvme/container-data/maintainerr
    containerPath: /opt/data

homepage:
  name: Maintainerr
  group: Indexer
  description: Media Maintainer
  icon: maintainerr.svg
  weight: 30
