image:
  repository: "ghcr.io/maintainerr/maintainerr"
  tag: "3.20.1@sha256:ce7ff52afa146dfc05c2c2304df8141e0086f14a803bdbef0d870e5b914f0dee"

ports:
  - name: main
    containerPort: 6246

gateway:
  host: maintainerr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: data
    hostPath: /srv/nvme/container-data/maintainerr
    containerPath: /opt/data

homepage:
  name: Maintainerr
  group: Indexer
  description: Media Maintainer
  icon: maintainerr.svg
  weight: 30
