image:
  repository: "pcjones/umlautadaptarr"
  tag: "0.7.5"

ports:
  - name: main
    containerPort: 5006

env:
  - SONARR__ENABLED: true
  - SONARR__HOST: http://sonarr:8989
  - RADARR__ENABLED: true
  - RADARR__HOST: http://radarr:7878

secretEnvs:
  - SONARR__APIKEY: AgBZ73Oly3+AwoQ9SswCrH1xNqjWRkpSWROhiP7FYY+v2z7FNXyVX+MATUTPA9Qjnw8yhIekYX2852dLD09k27KzuyKvq1Ax0EEwoZpidCVwACywj+GIgOaqoh2d/xeqKXO7pSENvaWc+1uKTwFB8KNSXbUVTVz7IxEmBV/E/utqjsewCWm5zcu6h+9V3D+5m/FyhZU2Bw7Z9utA7zcDNpFHwqOM9qttJcFc6jLZvvQHsO3iUoNFJ9uAb2uSU/BRKOBfYEKojjVOoXVXTkcglp35uXN0v31lucweYZWM5kyi/KyUQysTF8wKOWjlKwo6w3S1XyP+eKG31BYwqHuo4yzzvtpxG85aySQDXPYsTdzsp/Rfo2wpq2vyLE4YcbhGwJf62+DjvdZT7SxEmQ4JPx4rtyXqy+sfoLFvAJRLGjfz7q9ARTIBR6PDbvIOdEbxVqoVNI6saQNmVcPyxY9vvkeD5dxRb1MhGol4TlIQq5DQNCD6dNCJzGHxymik3YJSXH4qO9KEwXrcchu0a2lf8kHv5SfgqfFGJvk+OXyA7JULGD6cfZJeeZE6BjpDH7AGSnYDY8tWap/PZIMr8M69W+s2M6UBJNWczYtKPhPzt3uX4llLbhSz90hCIbIIJT0ByhSw+ss768x8MxmMwawomqXxUOBWXx9cHZ3anlxK5AdLezQf9ISLnUUGiCayKoi093bb1ShA3ewAN87xY686RjsuCNw457/WqXn54ideGUqIJQ==
  - RADARR__APIKEY: AgA+dRJx0KhI1202DAXMyexK+LVcXPt306y9Mqv4ZYDFKktuYw5CmNpsbILWgZzgc0imYbKRIhy4hSBippOARH28BpYKmyYybGZ/QMr4Pqsr0CfBl1TJbkjuMcc7uEhWZkJcK8FoA/BCvBI+tFqSO5ucF7BL+v9ZuKJbyRB50QgHH0MTuE9z4fXIRtKZz5Rl75u36t6fZTxA0EOhXRiUXr+dCxOykwJO6C3CBukwJSkoPHXBQhA/TR/g3uGh3gSk8y8FWCW2BoAXwLbjI+dI8BlMMsCkBNxcRibix+KPsin7i24qWRYaXPSUgNmgInt6QcciQvFwTo0LZhamcg41ZRFljNwVgWknlC6jblpdjVELg+NFa9EfDBz8vs832uozePufg8Dr+1Bl4dL9l0DgEzLDiZlNBoILnqLGzFdiXPJbgfPXBNnNNyW1wgXGdZKPSrf4YeV17KBarLDyqXBG+If9yFAnacMt8mpGp6fpEFdM0zoMHNwhZ/t2m/U/MrMsYCJ0kCPbVyrt8bukE8k7T17BE2JKokBRabqX65XpXlay+wwpMLBpxivv1UJq+E62/KP0mZ8Nu3J8lXUn8LTmUL2Z6fgn/UbRUSSIU4a0dnv0c4c+tE9ExDkU9/0idpag2AFqju3Cxo5lXkXSlrS+5s8G3xyB6h7M5gxvJLB9I1XxeeeZVlW3D6MlqhCLepV/kFi1GuwYTyjBu3BggtlmW51mCLETcHQhxsJzAd7j6yA/1Q==

