image:
  repository: "ghcr.io/tautulli/tautulli"
  tag: "v2.17.2@sha256:864245fb24830ef6516b5f383bf4d8ba37939ae2f0574dc0217ca02fba4301ff"

ports:
  - name: main
    containerPort: 8181

gateway:
  host: tautulli.wagner.gg

homepage:
  name: Tautulli
  group: Media
  description: Plex Statistic Board
  icon: tautulli.svg
  weight: 25

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/tautulli
    containerPath: /config
