image:
  repository: "ghcr.io/tautulli/tautulli"
  tag: "v2.18.0@sha256:f8b4a2693198b67497ecf4a35367eb7b40e91a7b225551b61587df164f6a99b1"

ports:
  - name: main
    containerPort: 8181

gateway:
  host: tautulli.wagner.gg

homepage:
  name: Tautulli
  group: Media
  description: Plex Statistic Board
  icon: tautulli.svg
  weight: 4

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/tautulli
    containerPath: /config
