image:
  repository: "ghcr.io/tautulli/tautulli"
  tag: "v2.17.0@sha256:9c73937390116e6875970f4c816ddfa9d905cc88f76f2ddbf4eaca2ea2715006"

ports:
  - name: main
    containerPort: 8181

gateway:
  host: tautulli.wagner.gg

homepage:
  name: Tautulli
  group: Media
  description: Plex Statistic Board
  icon: tautulli.svg
  weight: 25

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/tautulli
    containerPath: /config
