schedule:
  backup: "0 1 * * *"
  # cleanup: "0 6 2 * *"

restic:
  mode: init
  path: /srv/nvme/container-data
  exclude:
    - "*.log"
  iexclude:
    - radarr/MediaCover
    - lidarr/MediaCover
    - sonarr/MediaCover
    - tautulli/cache
    - stash/generated
    - stash/blobs
    - immich-data/thumbs
    - immich-data/encoded-video
    - Plex\ Media\ Server/Cache/PhotoTranscoder
    - jellyfin/data/trickplay
  basePath: AgBoW5ydic5wZjC5MA0Y3x59PJbOzpVXhh9bxz3UgI4Nf3sqKMWTr0E6VoIQ/7Y0dzWyCMr8mjwHYqHmg5fCWp+X5rVdpZ0+xEGiZqnjyrqcDHpGbN1zziN+5KzDzRgeCIsXirAiw05lPTHviKMKt6ZRBPO7SN/Yil7JkOzufkZzj87xfZ746eqejDe2Sty4BmD6efTjMfrwxueAbqsbMXgyLy+kRrvfCgmbqt1K9MKM9i6zmUfUDYyzpkVaDd08ZzgGLfOMT56Yj/r6PLyDN2sGpqwNIx0c7zm3fRn8zYJMRKQD/tCydybZTBawB2GWmbj5cKsL2586mDC1hddueWRESCiTsXZ4UuoyibqO3DCyooZxO2ExUvsyNkfSuI4e6/Zc9b4/IVB0ezW450vIbsrgp1odIliDE/VvYMLSKw1qyKwbP+/pENbZGW86gGn477qEjMluo9c0wjmwywFAp1FiP1fpTwlwbyv27WLzHsVOuJMCvF/3urjI2Ge8Dae7eAGmQNc77AJUeqTzPlF1G8AcAjRH4LVEIEwle1EPxkLVHQya8fF5XezHskfihsvLzhYgNQfTcxyKoMwEQIad2SBJMsz3OKEAHbN4Nyh4PsgmhZ9H7ScPpD9rnv88YKGfiiJlNWse3/QW1W2T3uToqaSK4xsLyftVeC+zwcAlvVPGQvuFwkxGKzWejWc75pa7Wo2VxwxscztuFQ4Dptq1eeiTkoGHkDZf6KfOkz7l3S8Kjg==
  accessKeyId: AgAgS8PoA2/nzIXEHP0ewV8qnjsi47z/lbjpwf0Sr6/s6A0J33ABZNISuuNHH+RoALTv41LGFDFipbtqa7GV2tKoP7hYIr27RsL3jSkVRUoQPi+YYAlsorpnxcSGAvUpDghG4hLZKNyB0VMFf3ZYyTKIjQdaxhKbdRyN8qNwfxhJQcFIqnGB/7w6F6totmMxu3SW15pdHk3Cg3H0XsdiEnkE/qUQU8+SdujaLws0ardJxKQi9BTXz4+QMnWKNPfRtI8PtH0wAxEv11Zrfxzhe0lRUFmBZJn7DU2MBhZhpubd/GYklOluxVT7a3WIQaVkHrgrEvXFvDDrGdN875VV6zKkP8eFZ3Tc28HUX6Ajv1cDWNBxJdg25gBx5Oxp4lNRWRgmyhpqYYYskwK4nF+7BUbYrOuYx24pXICBwz961l8IzLb8xowNcax4vZrAoaQ+Z0N+Ol2bkpYofl8BVfdizDV2bnPHlJbQmGxbwkh5HiBiqTgbeEuDKtpERku2lIlVUFWzm7bfJc0UDn60MLrjp8z2r3sTd2O0jIxapI5rW012bs6js9slSllRmdqgeEteLUGkkeDo89+wcHyV+yG8//CUOf0sS181Bu/XcJcOyDvpohXjSvOSotPXLcg7Y8LJp49XqE50oVnp6NlRKEt7r7HAZuwWEwsom2je4Dq29tzeic3ZyFEL2rVc3qFwudXp0vli76h7v1921BebNmtEeoH1
  secretKeyId: AgA5TRQVP/jAvjmCcGFPOKXyjDUwnRQcKN2ivbDMTd4r9uRL5UJ9RCvMeODOElaB3zQA8Cl61gUkBWRuHGmPJh6bUJpNiOM9R18gNQEaqvpkTU0sMjNwMZqABQe40glB6ji/aQhFXVzVa4VFykmuOcUlWdfguBFCqocmLuKf6VR8qZbgeZEr7BMT3WtB9mmY6tN61aCMH+u+5fYVBQxikJIb180tcZFrp8cRXi/SELxf1rKkROhHEiJeHmGxYgoUgViQzpd+eJkLgNTGKWSYJaTKC1CVRVkOhVmWf7V5iuPphLqILwsuYdVdcMQrDM8i0Y4t4Ijg0Sy2UPCpMc9QzdVMCiY3mMUwzbsvcL9OERwG5dwi3Wm6j37Nz/4Wmjh10uOoEizsHERoJDyYhwAo/1mj2rbqHbKLRzOHN0csLW5jPgFxLjndCliKGksifeF8BTWdxbSyTa7IRY2i2onLBvkxQgQaAzC79UxP6mgj3vu6TzrhLGOyySiKd9T++YpWXrbhyBJXZk/YoScwNpYaxbyZvCO/GZ5ts+PF5iXZVfyDxvMd+6o2C4+ukS9aJX/jpfXxc9hVcqwd1JFMjzWAOPbI4XJBmGctNhDOBtwXOS68eyqeVSiY7HwhqQErvyKAGEHl87Ghtux3Mo2qEl8amt57XYpA8xXY79lLjWovBjJjkPB6snZuUVR2cNP019DcXCEMsa0/lVlH8YCCDoX8IBEtE3FjA0WxqAilQlzJLMN6nXOHKRSejzp4Am8lwpFeWzc=
