schedule:
  backup: "0 1 * * *"
  # cleanup: "0 6 2 * *"

restic:
  mode: init
  path: /srv/nvme/container-data
  exclude:
    - "*.log"
  iexclude:
    - radarr/MediaCover
    - lidarr/MediaCover
    - sonarr/MediaCover
    - tautulli/cache
    - stash/generated
    - stash/blobs
    - immich-data/thumbs
    - immich-data/encoded-video
    - Plex\ Media\ Server/Cache/PhotoTranscoder
    - jellyfin/data/trickplay
  basePath: AgCwAqwSIpLfX6P18wsz5NuGO3Gv4A13EQMlxd5YRWnefCynpq9hII7KJYP0zxOfqha/gJnNiZZxKMT+SxLvsKhErRPQG/6sMYsCBrMU0II4rvyMSTWCu9fZIcSZXsNNZ1RqCzeVTswz3N/CcPwb55NQzEEI6wogh7mTQ2C7w3XmdW8LNrIWC3UIWc6pJ1HVKlM2jQmfMlJNgd8p3S7Eg/kOfa5w4pYhLFZ6/9SIzYgW3z1ZYh7erk00UmZwWTX7abvZFZLapu0/JG4ODI//yqnRD14fJwrNaGzNz5dfJ8cOVj3QDefhgV8fe2W4E3EAoLXUVaKHZIYVgTzGzX9+RwItT7iHxLva4xi9tC6q1zfGoHga61XdyMhhuZpfbn8iEUi0G9Y/b90oYMQUV2iR5QI05FQshQVelUBqhMUiK/8x90iEzpA3lqar/ghE4doKGFW3aMWa4u9nJt81gzluA0VxO1Uwlip/7PqZ/h+zU1ULQzEo/wvPjThfeQsKBghRSmSM6W7mKhCSBJCubdIpo4G0cgM9Wh4Zv6kOyiKnQLk8ecEMHWWE8HxWJnKwPkVcC4Se9b8zSu03QoJsheBXIvL71g+LAt0eMgBfNdBlqqkh1tCm8JxwdOueQDQFzamT6VympJ9XnNFG1PQLWimHexTmiiLEV4aQePlSYPM1gU5cBhhSOOteYJukAiifD0doqr9d94gBDoIi0SiaYCURmn8axHTedtupRI3qUSRAtG2/iTnDaw==
  accessKeyId: AgAgS8PoA2/nzIXEHP0ewV8qnjsi47z/lbjpwf0Sr6/s6A0J33ABZNISuuNHH+RoALTv41LGFDFipbtqa7GV2tKoP7hYIr27RsL3jSkVRUoQPi+YYAlsorpnxcSGAvUpDghG4hLZKNyB0VMFf3ZYyTKIjQdaxhKbdRyN8qNwfxhJQcFIqnGB/7w6F6totmMxu3SW15pdHk3Cg3H0XsdiEnkE/qUQU8+SdujaLws0ardJxKQi9BTXz4+QMnWKNPfRtI8PtH0wAxEv11Zrfxzhe0lRUFmBZJn7DU2MBhZhpubd/GYklOluxVT7a3WIQaVkHrgrEvXFvDDrGdN875VV6zKkP8eFZ3Tc28HUX6Ajv1cDWNBxJdg25gBx5Oxp4lNRWRgmyhpqYYYskwK4nF+7BUbYrOuYx24pXICBwz961l8IzLb8xowNcax4vZrAoaQ+Z0N+Ol2bkpYofl8BVfdizDV2bnPHlJbQmGxbwkh5HiBiqTgbeEuDKtpERku2lIlVUFWzm7bfJc0UDn60MLrjp8z2r3sTd2O0jIxapI5rW012bs6js9slSllRmdqgeEteLUGkkeDo89+wcHyV+yG8//CUOf0sS181Bu/XcJcOyDvpohXjSvOSotPXLcg7Y8LJp49XqE50oVnp6NlRKEt7r7HAZuwWEwsom2je4Dq29tzeic3ZyFEL2rVc3qFwudXp0vli76h7v1921BebNmtEeoH1
  secretKeyId: AgA5TRQVP/jAvjmCcGFPOKXyjDUwnRQcKN2ivbDMTd4r9uRL5UJ9RCvMeODOElaB3zQA8Cl61gUkBWRuHGmPJh6bUJpNiOM9R18gNQEaqvpkTU0sMjNwMZqABQe40glB6ji/aQhFXVzVa4VFykmuOcUlWdfguBFCqocmLuKf6VR8qZbgeZEr7BMT3WtB9mmY6tN61aCMH+u+5fYVBQxikJIb180tcZFrp8cRXi/SELxf1rKkROhHEiJeHmGxYgoUgViQzpd+eJkLgNTGKWSYJaTKC1CVRVkOhVmWf7V5iuPphLqILwsuYdVdcMQrDM8i0Y4t4Ijg0Sy2UPCpMc9QzdVMCiY3mMUwzbsvcL9OERwG5dwi3Wm6j37Nz/4Wmjh10uOoEizsHERoJDyYhwAo/1mj2rbqHbKLRzOHN0csLW5jPgFxLjndCliKGksifeF8BTWdxbSyTa7IRY2i2onLBvkxQgQaAzC79UxP6mgj3vu6TzrhLGOyySiKd9T++YpWXrbhyBJXZk/YoScwNpYaxbyZvCO/GZ5ts+PF5iXZVfyDxvMd+6o2C4+ukS9aJX/jpfXxc9hVcqwd1JFMjzWAOPbI4XJBmGctNhDOBtwXOS68eyqeVSiY7HwhqQErvyKAGEHl87Ghtux3Mo2qEl8amt57XYpA8xXY79lLjWovBjJjkPB6snZuUVR2cNP019DcXCEMsa0/lVlH8YCCDoX8IBEtE3FjA0WxqAilQlzJLMN6nXOHKRSejzp4Am8lwpFeWzc=
