image:
  repository: "fireflyiii/data-importer"
  tag: "version-2.3.4@sha256:26459e1f014544f1ae56d1beed9c6a0ddf208b1eaa24cf11fa77ebd1f51422c8"

ports:
  - name: main
    containerPort: 8080

gateway:
  host: firefly-import.wagner.gg

health:
  path: /health

homepage:
  name: Firefly III Importer
  group: Personal & Finance
  description: Data Importer for Firefly III
  icon: firefly
  weight: 3

envs:
  - TRUSTED_PROXIES: "**"
  - FIREFLY_III_URL: http://firefly:8080
  - VANITY_URL: https://firefly.wagner.gg
  - FIREFLY_III_CLIENT_ID: 019f7995-2373-72db-b416-127602dd8ddb
