image:
  repository: "fireflyiii/data-importer"
  tag: "version-2.3.4@sha256:1379248292e1a0820e73714f3676b6de3909178c3017fce7aec0a9d20ffb8dec"

ports:
  - name: main
    containerPort: 8080

gateway:
  host: firefly-import.wagner.gg

health:
  path: /

homepage:
  name: Firefly III Importer
  group: Organization
  description: Data Importer for Firefly III
  icon: firefly
  weight: 3

envs:
  - TRUSTED_PROXIES: "**"
  - FIREFLY_III_URL: http://firefly:8080
  - VANITY_URL: https://firefly.wagner.gg
  - FIREFLY_III_CLIENT_ID: 019f7479-172c-71f4-adcb-0e53a80575dc
