image:
  repository: "ghcr.io/syncthing/syncthing"
  tag: "2.0.16@sha256:4a961394ca471f4e48f31ad2cef50697e502c8799e2e98477a1c3844e0c5bc54"

ports:
  - name: main
    containerPort: 8384
  - name: tcp-transfer
    containerPort: 22000
    hostPort: 22000
    protocol: TCP
  - name: udp-transfer
    containerPort: 22000
    hostPort: 22000
    protocol: UDP
  - name: discovery
    containerPort: 21027
    hostPort: 21027
    protocol: UDP

gateway:
  host: syncthing.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

homepage:
  name: Syncthing
  group: Cloud
  description: Syncing files
  icon: syncthing.svg
  weight: 40

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/syncthing
    containerPath: /var/syncthing
  - name: data
    hostPath: /srv/nvme/niklas/Sync
    containerPath: /data/sync
  - name: pictures
    hostPath: /srv/nvme/pictures
    containerPath: /data/pictures
