image:
  repository: "ghcr.io/hotio/prowlarr"
  tag: "release-2.4.0.5397@sha256:ef9bd520de4f269993fabc3dbeb74eb192bc773d5d7db1d564730d5475ffd47a"

ports:
  - name: main
    containerPort: 9696

gateway:
  host: prowlarr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/prowlarr
    containerPath: /config

homepage:
  name: Prowlarr
  group: Indexer
  description: Index Manager
  icon: prowlarr.svg
  weight: 10
