image:
  repository: "ghcr.io/hotio/prowlarr"
  tag: "release-2.5.2.5491@sha256:7f8321ee71b97bc023ffecacda0fd20bb04493d5020ed0b1fe27cb6cfa92272e"

ports:
  - name: main
    containerPort: 9696

gateway:
  host: prowlarr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/prowlarr
    containerPath: /config

homepage:
  name: Prowlarr
  group: Indexer
  description: Index Manager
  icon: prowlarr.svg
  weight: 10
