image:
  repository: "ghcr.io/hotio/prowlarr"
  tag: "release-2.6.5.5623@sha256:63b7ff5773278d3a006f698e80db391ce5abe9b10663f399cc2732785ea520f9"

ports:
  - name: main
    containerPort: 9696

gateway:
  host: prowlarr.wagner.gg

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/prowlarr
    containerPath: /config

homepage:
  name: Prowlarr
  group: Manager
  description: Index Manager
  icon: prowlarr.svg
  weight: 1
