image:
  repository: "ghcr.io/curl/curl-container/curl-multi"
  tag: "8.20.0@sha256:b3f1fb2a51d923260350d21b8654bbc607164a987e2f7c84a0ac199a67df812a"

schedule: "0 3 * * *"

args:
  - -v
  - --silent
  - --remote-header-name
  - --remote-name
  - --output-dir
  - /data
  - https://darekkay.com/service/trakt/trakt.php?username=Skaronator

hostPaths:
  - name: data
    hostPath: /srv/hdd/backup/Trakt
    containerPath: /data
