image:
  repository: "ghcr.io/curl/curl-container/curl-multi"
  tag: "8.19.0@sha256:9a6f6a17667960e077f1b153009aaf18ac99a622221084e1938a45a06fff057a"

schedule: "0 3 * * *"

args:
  - -v
  - --silent
  - --remote-header-name
  - --remote-name
  - --output-dir
  - /data
  - https://darekkay.com/service/trakt/trakt.php?username=Skaronator

hostPaths:
  - name: data
    hostPath: /srv/hdd/backup/Trakt
    containerPath: /data
