image:
  repository: "ghcr.io/seerr-team/seerr"
  tag: "v3.2.0@sha256:c4cbd5121236ac2f70a843a0b920b68a27976be57917555f1c45b08a1e6b2aad"

ports:
  - name: main
    containerPort: 5055

gateway:
  host: seerr.wagner.gg
  public: true

health:
  path: /api/v1/status

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/seerr
    containerPath: /app/config

homepage:
  name: Seerr
  group: Media
  description: Media Requests from User
  icon: seerr.svg
  weight: 1
