image:
  repository: "ghcr.io/seerr-team/seerr"
  tag: "v3.1.1@sha256:d535391db3b5a22ce02241e6d7a50ca714e75d927e46aa20456b77fa051cbf52"

ports:
  - name: main
    containerPort: 5055

gateway:
  host: seerr.wagner.gg
  public: true

health:
  path: /api/v1/status

envs:
  - PUID: 5000
  - PGID: 5000

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/seerr
    containerPath: /app/config

homepage:
  name: Seerr
  group: Media
  description: Media Requests from User
  icon: seerr.svg
  weight: 1
