policy: sync
registry: noop
interval: 15s

extraArgs:
  - --gateway-name=private

sources:
  - gateway-httproute
  - crd

triggerLoopOnEvent: true

provider:
  name: webhook
  webhook:
    image:
      repository: ghcr.io/muhlba91/external-dns-provider-adguard
      tag: v11.1.1@sha256:b3dfe851982b59a36bf2e15f42ca4015b7ef39ddf7a808c39a855a05a61b5892
    env:
      - name: ADGUARD_URL
        value: http://192.168.0.2
      - name: ADGUARD_USER
        valueFrom:
          secretKeyRef:
            name: external-dns-adguard-home
            key: username
      - name: ADGUARD_PASSWORD
        valueFrom:
          secretKeyRef:
            name: external-dns-adguard-home
            key: password
