policy: sync
registry: noop
interval: 15s

extraArgs:
  - --gateway-name=private

sources:
  - gateway-httproute
  - crd

triggerLoopOnEvent: true

provider:
  name: webhook
  webhook:
    image:
      repository: ghcr.io/muhlba91/external-dns-provider-adguard
      tag: v11.2.0@sha256:a119f729b16d435769aefcd9d4be149d4be7142848439bafd45e4045aa0b2e4e
    env:
      - name: ADGUARD_URL
        value: http://192.168.0.2
      - name: ADGUARD_USER
        valueFrom:
          secretKeyRef:
            name: external-dns-adguard-home
            key: username
      - name: ADGUARD_PASSWORD
        valueFrom:
          secretKeyRef:
            name: external-dns-adguard-home
            key: password
