image:
  repository: "ghcr.io/justarchinet/archisteamfarm"
  tag: "6.3.9.3@sha256:3545a19757a66c749a93cb4ea431aed85fe51979776a4a8378acf35126aae83f"

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/archisteamfarm-config
    containerPath: /app/config
  - name: plugins
    hostPath: /srv/nvme/container-data/archisteamfarm-plugins
    containerPath: /app/plugins

ports:
  - name: main
    containerPort: 1242

gateway:
  host: asf.wagner.gg

homepage:
  name: ArchiSteamFarm
  group: Cloud
  description: Automated Steam Card Farming
  icon: archisteamfarm.png
  weight: 50
