image:
  repository: "ghcr.io/justarchinet/archisteamfarm"
  tag: "6.3.10.0@sha256:b8436bb7443c6f0bef32daa176bffad8fb37cdc05dc4034db95e4abfc89e3d81"

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/archisteamfarm-config
    containerPath: /app/config
  - name: plugins
    hostPath: /srv/nvme/container-data/archisteamfarm-plugins
    containerPath: /app/plugins

ports:
  - name: main
    containerPort: 1242

gateway:
  host: asf.wagner.gg

homepage:
  name: ArchiSteamFarm
  group: Home & Utilities
  description: Automated Steam Card Farming
  icon: archisteamfarm.png
  weight: 5
