image:
  repository: "ghcr.io/justarchinet/archisteamfarm"
  tag: "6.3.7.0@sha256:c4d0f409594b211f224834daccc1a6922f149d9a990e3b991579c7446ce94f8b"

hostPaths:
  - name: config
    hostPath: /srv/nvme/container-data/archisteamfarm-config
    containerPath: /app/config
  - name: plugins
    hostPath: /srv/nvme/container-data/archisteamfarm-plugins
    containerPath: /app/plugins

ports:
  - name: main
    containerPort: 1242

gateway:
  host: asf.wagner.gg

homepage:
  name: ArchiSteamFarm
  group: Cloud
  description: Automated Steam Card Farming
  icon: archisteamfarm.png
  weight: 50
