apiVersion: policies.kyverno.io/v1
kind: DeletingPolicy
metadata:
  name: cleanup-stuck-pods
spec:
  schedule: "*/5 * * * *"
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
  conditions:
    - name: minimum-age
      expression: |
        time.now() - timestamp(object.metadata.creationTimestamp) > duration("15m")
    - name: stuck-pods
      expression: |
        object.status.reason == 'UnexpectedAdmissionError' ||
        object.status.?initContainerStatuses.orValue([]).exists(s, 
          s.state.?terminated.?reason.orValue('') == 'ContainerStatusUnknown') ||
        object.status.?containerStatuses.orValue([]).exists(s, 
          s.state.?terminated.?reason.orValue('') == 'ContainerStatusUnknown')
