apiVersion: policies.kyverno.io/v1
kind: DeletingPolicy
metadata:
  name: cleanup-stuck-pods
spec:
  schedule: '* * * * *'
  matchConstraints:
    resourceRules:
      - apiGroups: ['']
        apiVersions: ['v1']
        operations: ['*']
        resources: ['pods']
        scope: 'Namespaced'
    namespaceSelector:
      matchLabels:
        environment: test
  conditions:
    - name: stuck-pods
      expression: >
        object.status.reason == 'UnexpectedAdmissionError' ||
        (object.status.?initContainerStatuses.orValue([]).exists(s, 
          s.state.?terminated.reason == 'ContainerStatusUnknown'))
    - name: minimum-age
      expression: >
        timestamp(object.metadata.creationTimestamp) < request.time - duration('10m')
