image:
  repository: "ghcr.io/sethforprivacy/simple-monerod"
  tag: "v0.18.4.6@sha256:ed9299d73634a13f10de85e63d104276bf5e4ce5175ee4cc16f64f4bbeacbbd4"

args:
  - --rpc-restricted-bind-ip=0.0.0.0
  - --rpc-restricted-bind-port=18089
  - --no-igd
  - --no-zmq

hostPaths:
  - name: data
    hostPath: /srv/nvme/scrap-data/monero
    containerPath: /home/monero/.bitmonero

ports:
  - name: main
    containerPort: 18089
  - name: p2p
    containerPort: 18080

gateway:
  host: monero.wagner.gg

health:
  path: /get_height

securityContext:
  runAsUser: 5000
