image:
  repository: "ghcr.io/sethforprivacy/simple-monerod"
  tag: "v0.18.5.0@sha256:54b68cae321119c794930af32e4fec6772d9bd9e5a2b1a2e2b8efcf49ae68d8f"

args:
  - --rpc-restricted-bind-ip=0.0.0.0
  - --rpc-restricted-bind-port=18089
  - --no-igd
  - --no-zmq

hostPaths:
  - name: data
    hostPath: /srv/nvme/scrap-data/monero
    containerPath: /home/monero/.bitmonero

ports:
  - name: main
    containerPort: 18089
  - name: p2p
    containerPort: 18080

gateway:
  host: monero.wagner.gg

health:
  path: /get_height

securityContext:
  runAsUser: 5000
