image:
  repository: "lancachenet/monolithic"
  tag: "latest@sha256:a5f93cef3a4c48c63e9f09883ac7a3961621db56974427110d9aeb4f36af9360"

hostPaths:
  - name: data
    hostPath: /srv/nvme/scrap-data/lancache
    containerPath: /data/cache

ports:
  - name: main
    containerPort: 80
  - name: https
    containerPort: 443

service:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.252
  loadBalancerClass: metallb

envs:
  - CACHE_MAX_AGE: 365d
  - CACHE_INDEX_SIZE: 500m
  - MIN_FREE_DISK: 100g
  - CACHE_DISK_SIZE: 1000g

health:
  type: TCP
