image:
  repository: "lancachenet/monolithic"
  tag: "latest@sha256:37f28b362c939a333f3e4f12aa8ca80604cf75050b2f190d0ad972b2fedce00e"

hostPaths:
  - name: data
    hostPath: /srv/nvme/scrap-data/lancache
    containerPath: /data/cache

ports:
  - name: main
    containerPort: 80
  - name: https
    containerPort: 443

service:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.252
  loadBalancerClass: metallb

envs:
  - CACHE_MAX_AGE: 365d
  - CACHE_INDEX_SIZE: 500m
  - MIN_FREE_DISK: 100g
  - CACHE_DISK_SIZE: 1000g

health:
  type: TCP
