image:
  repository: "bitcoin/bitcoin"
  tag: "30.2-alpine@sha256:098e163aa9fd7958688a55bb9a2660d02c1b4f2701b827f4884a210569d25ba6"

command:
  - "bitcoind"

args:
  # basic
  - "-datadir=/data"
  - "-server=1"
  - "-disablewallet=1"
  - "-txindex=1"
  - "-blockfilterindex=1"
  # rpc
  - "-rpcbind=:8332"
  - "-rpcallowip=0.0.0.0/0"
  - "-zmqpubrawtx=tcp://0.0.0.0:28332"
  - "-zmqpubrawblock=tcp://0.0.0.0:28333"

hostPaths:
  - name: data
    hostPath: /srv/nvme/scrap-data/bitcoin
    containerPath: /data

ports: 
- name: rpc
  containerPort: 8332
- name: p2p
  containerPort: 8333
- name: zmqtx
  containerPort: 28332
- name: zmqblock
  containerPort: 28333

health:
  port: rpc
  type: TCP

securityContext:
  runAsUser: 5000
