image:
  repository: "bitcoin/bitcoin"
  tag: "31.0-alpine@sha256:822bbb5ab86a39c8db0d7ab12cc6f16f70a62934dd778e1ff70442cacbb747cb"

command:
  - "bitcoind"

args:
  # basic
  - "-datadir=/data"
  - "-server=1"
  - "-disablewallet=1"
  - "-txindex=1"
  - "-blockfilterindex=1"
  # rpc
  - "-rpcbind=:8332"
  - "-rpcallowip=0.0.0.0/0"
  - "-zmqpubrawtx=tcp://0.0.0.0:28332"
  - "-zmqpubrawblock=tcp://0.0.0.0:28333"

hostPaths:
  - name: data
    hostPath: /srv/nvme/scrap-data/bitcoin
    containerPath: /data

ports: 
- name: rpc
  containerPort: 8332
- name: p2p
  containerPort: 8333
- name: zmqtx
  containerPort: 28332
- name: zmqblock
  containerPort: 28333

health:
  port: rpc
  type: TCP

securityContext:
  runAsUser: 5000
